import { Link } from "wouter";
import { motion } from "motion/react";
import { ArrowUpRight, FileCheck2, Lock, Mic2, ShieldAlert } from "lucide-react";

/**
 * The Sovereign Audio Protocol, explained on the public landing page.
 *
 * Written for the person with the problem, not for the engineer who solved it:
 * the Copyright Office now requires you to disclaim machine-generated material,
 * and nobody can tell from a finished mix which parts those are. Everything
 * below leads with that, and keeps the claims to what the system actually does.
 */

/**
 * The protocol has two halves and the page should say so: audio coming in is
 * examined, audio going out is sealed. `side` labels which half each step is.
 */
const STEPS = [
  {
    n: "01",
    side: "Coming in",
    icon: Mic2,
    title: "Drop the track in",
    body: "One file. It is fingerprinted the moment it lands, before anything touches it, so the chain of custody starts at your desk.",
  },
  {
    n: "02",
    side: "Coming in",
    icon: ShieldAlert,
    title: "It pulls the record apart",
    body: "Vocals, drums, bass and instruments are separated on your own hardware, then each one is examined on its own for the physical traces of a human performance.",
  },
  {
    n: "03",
    side: "Coming in",
    icon: FileCheck2,
    title: "You get the filing language",
    body: "A stem-by-stem finding, and the exact wording to paste into the Copyright Office application — what to disclaim, what to claim — with a one-page examiner report behind it.",
  },
  {
    n: "04",
    side: "Going out",
    icon: Lock,
    title: "Every export leaves sealed",
    body: "Four versions render at once — vault, streaming master, sync mix, AI-licensing copy — each carrying that record inside the file, signed, so tampering shows.",
  },
];

const AUDIENCES = [
  {
    who: "Artists and producers",
    need: "File with confidence. Claim the performance you actually gave, disclaim what you did not, and stop guessing at the line between them.",
  },
  {
    who: "Labels and publishers",
    need: "Know what you are buying. Run a catalog through before acquisition instead of inheriting an unregistrable master.",
  },
  {
    who: "Sync and licensing",
    need: "Warrant what you are clearing. The instrumental ships pre-separated, with its provenance attached to the file itself.",
  },
  {
    who: "AI licensing and compliance",
    need: "Set terms in the audio. The machine-ingestion copy states whether training is permitted, in a header a crawler can read.",
  },
];

export function Authorship() {
  return (
    <section
      id="authorship"
      className="relative overflow-hidden border-t border-obsidian-line py-28"
    >
      <div
        className="absolute inset-0"
        aria-hidden
        style={{
          background: "radial-gradient(ellipse at 15% 0%, rgba(197,160,89,0.09), transparent 55%)",
        }}
      />

      <div className="relative mx-auto max-w-[1200px] px-6">
        {/* The problem, stated plainly. */}
        <div className="grid items-start gap-14 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,1fr)] lg:gap-20">
          <div>
            <p className="eyebrow">Authorship &amp; Provenance</p>
            <motion.h2
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-80px" }}
              transition={{ duration: 0.7 }}
              className="mt-3 font-display text-4xl leading-[1.04] md:text-5xl lg:text-[3.4rem]"
            >
              The Copyright Office will register your record.{" "}
              <span className="gold-text">But only if you can say which parts you made.</span>
            </motion.h2>

            <div className="mt-8 max-w-xl space-y-5 leading-relaxed text-muted">
              <p>
                Since 2023 the U.S. Copyright Office has asked applicants to disclose material
                generated by AI and exclude it from the claim. Register a track without
                disclaiming, and the registration can be refused — or cancelled later, after you
                have already relied on it.
              </p>
              <p>
                The trouble is that nobody can tell, from a finished mixed record, which parts a
                person performed and which a model produced. So artists guess. Guess high and you
                put the registration at risk; guess low and you sign away rights you genuinely own.
              </p>
              <p className="text-bone">
                The Sovereign Audio Protocol answers that question with measurements instead of
                opinion — and hands you the paperwork that goes with the answer.
              </p>
            </div>
          </div>

          {/* Who it is for. */}
          <div className="space-y-px bg-obsidian-line lg:mt-16">
            {AUDIENCES.map((a, i) => (
              <motion.div
                key={a.who}
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                className="border-l-2 border-gold/70 bg-obsidian p-6"
              >
                <h3 className="font-display text-xl text-bone">{a.who}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-muted">{a.need}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* How it runs — four steps, because it genuinely is a sequence. */}
        <div className="mt-24">
          <p className="eyebrow">Audio in, audio out</p>
          <h3 className="mt-3 max-w-2xl font-display text-3xl leading-[1.1] md:text-4xl">
            Coming in, it is examined. Going out, it is sealed.
          </h3>
          <p className="mt-4 max-w-2xl leading-relaxed text-muted">
            Three steps establish who made what. The fourth writes that finding into every
            file you ship, so the answer travels with the audio instead of living in a PDF
            somebody has to go and find.
          </p>

          <div className="mt-12 grid gap-px bg-obsidian-line sm:grid-cols-2 lg:grid-cols-4">
            {STEPS.map((s, i) => (
              <motion.div
                key={s.n}
                initial={{ opacity: 0, y: 18 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-60px" }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
                className="flex flex-col bg-obsidian p-7"
              >
                <div className="flex items-center gap-3">
                  <s.icon className="h-5 w-5 shrink-0 text-gold" aria-hidden />
                  <span className="font-mono text-xs text-gold">{s.n}</span>
                  <span
                    className={`ml-auto rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.14em] ${
                      s.side === "Coming in"
                        ? "border-obsidian-line text-muted"
                        : "border-gold/40 bg-gold/10 text-gold"
                    }`}
                  >
                    {s.side}
                  </span>
                </div>
                <h4 className="mt-4 font-display text-xl leading-tight text-bone">{s.title}</h4>
                <p className="mt-2 text-sm leading-relaxed text-muted">{s.body}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* What the finding actually looks like — concrete beats abstract. */}
        <div className="mt-20 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)] lg:gap-16">
          <div>
            <p className="eyebrow">What comes back</p>
            <h3 className="mt-3 font-display text-3xl leading-[1.1]">
              A verdict per stem, and the reasoning behind it
            </h3>
            <p className="mt-5 leading-relaxed text-muted">
              Each source is scored on measurable things: the pitch jitter of a real voice, the few
              milliseconds a drummer sits off the grid, whether a room is audible behind the
              performance, whether the top octave was reconstructed rather than recorded.
            </p>
            <p className="mt-4 leading-relaxed text-muted">
              Every number is published with the weight it carried. Nothing is decided by a model,
              and the same file always produces the same result — which is what lets a finding
              survive being questioned.
            </p>
          </div>

          {/* An illustrative finding. Marked as an example, never as real data. */}
          <div className="card-surface rounded-2xl p-6">
            <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted">
              Example finding · illustration only
            </p>
            <div className="mt-5 space-y-3">
              {[
                { stem: "Vocals", verdict: "Human performance", status: "Claimable", tone: "verified", pct: 92 },
                { stem: "Drums", verdict: "AI generated", status: "Must exclude", tone: "danger", pct: 8 },
                { stem: "Bass & harmony", verdict: "Human directed", status: "Partial claim", tone: "gold", pct: 57 },
              ].map((row) => (
                <div key={row.stem} className="rounded-xl border border-obsidian-line bg-obsidian/60 p-4">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <span className="font-display text-lg text-bone">{row.stem}</span>
                    <span
                      className={`rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase tracking-[0.14em] ${
                        row.tone === "verified"
                          ? "border-verified/40 bg-verified/10 text-verified"
                          : row.tone === "danger"
                            ? "border-danger/40 bg-danger/10 text-danger"
                            : "border-gold/40 bg-gold/10 text-gold"
                      }`}
                    >
                      {row.status}
                    </span>
                  </div>
                  <p className="mt-1 font-mono text-[10px] uppercase tracking-[0.14em] text-muted">
                    {row.verdict}
                  </p>
                  <div className="mt-3 h-1.5 w-full overflow-hidden rounded-full bg-obsidian-line">
                    <div
                      className={`h-full ${
                        row.tone === "verified"
                          ? "bg-verified"
                          : row.tone === "danger"
                            ? "bg-danger"
                            : "bg-gold"
                      }`}
                      style={{ width: `${row.pct}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-5 rounded-xl border border-gold/25 bg-gold/[0.05] p-4">
              <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-muted">
                Ready to paste into the application
              </p>
              <p className="mt-2 font-mono text-[11px] leading-relaxed text-bone/90">
                “Applicant expressly disclaims copyright in machine-generated rhythmic and
                percussion elements… Applicant claims the original vocal performance, the musical
                arrangement, and the sound recording as fixed.”
              </p>
            </div>
          </div>
        </div>

        {/* Honest boundary + the way in. */}
        <div className="mt-20 flex flex-col items-start gap-6 border-t border-obsidian-line pt-10 sm:flex-row sm:items-center sm:justify-between">
          <p className="max-w-2xl text-sm leading-relaxed text-muted">
            The protocol runs entirely on your own infrastructure — no audio is sent to a third
            party at any point. It states measurements and the conclusions drawn from them; it is
            not legal advice, and the Copyright Office makes its own determination on every
            application.
          </p>
          <Link
            to="/sovereign-protocol"
            className="flex shrink-0 items-center gap-2 bg-gold px-8 py-4 font-mono text-xs uppercase tracking-[0.2em] text-obsidian transition-colors hover:bg-gold-bright"
          >
            Open the console <ArrowUpRight size={15} />
          </Link>
        </div>
      </div>
    </section>
  );
}
