import { pngChunks, sniffFormat, type ImageFormat } from "./container";

/**
 * Read the AI disclosures a file already carries.
 *
 * This is inventory, not removal: whatever is found here is recorded in the
 * credential and left in the file. The credential then says who made the
 * creative decisions; the disclosure keeps saying which tools were involved.
 *
 * Invisible pixel watermarks (SynthID and similar) can only be read by the
 * vendor's own detector, so their absence here is not evidence of absence —
 * the result says so rather than implying a clean file.
 */

export type DisclosureKind =
  | "c2pa_manifest"
  | "iptc_digital_source_type"
  | "generator_parameters"
  | "software_tag";

export type Disclosure = {
  kind: DisclosureKind;
  /** Where in the container it was found. */
  location: string;
  /** Short human-readable reading of what it says. */
  detail: string;
};

export type DisclosureReport = {
  format: ImageFormat;
  disclosures: Disclosure[];
  /** Always true: pixel-level watermarks are outside what a container read can see. */
  invisible_watermarks_unchecked: true;
};

const DIGITAL_SOURCE_TYPES: Record<string, string> = {
  trainedAlgorithmicMedia: "Generated by a trained AI model",
  compositeWithTrainedAlgorithmicMedia: "Composite including AI-generated elements",
  algorithmicallyEnhanced: "Algorithmically enhanced",
  compositeSynthetic: "Composite of synthetic elements",
  algorithmicMedia: "Algorithmically generated",
};

const GENERATOR_KEYS = new Set(["parameters", "prompt", "workflow", "Dream", "sd-metadata", "invokeai_metadata"]);

function latin1(bytes: Uint8Array): string {
  let s = "";
  for (let i = 0; i < bytes.byteLength; i += 0x8000) {
    s += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return s;
}

function indexOfBytes(haystack: Uint8Array, needle: string, from = 0): number {
  const n = new TextEncoder().encode(needle);
  outer: for (let i = from; i <= haystack.byteLength - n.byteLength; i++) {
    for (let j = 0; j < n.byteLength; j++) if (haystack[i + j] !== n[j]) continue outer;
    return i;
  }
  return -1;
}

function pngTextEntries(bytes: Uint8Array): { key: string; value: string }[] {
  const out: { key: string; value: string }[] = [];
  for (const chunk of pngChunks(bytes)) {
    if (chunk.type !== "tEXt" && chunk.type !== "iTXt") continue;
    const nul = chunk.data.indexOf(0);
    if (nul <= 0) continue;
    const key = new TextDecoder().decode(chunk.data.subarray(0, nul));
    let valueStart = nul + 1;
    if (chunk.type === "iTXt") {
      valueStart = chunk.data.indexOf(0, nul + 3) + 1;
      valueStart = chunk.data.indexOf(0, valueStart) + 1;
    }
    out.push({ key, value: new TextDecoder().decode(chunk.data.subarray(valueStart)) });
  }
  return out;
}

export function detectDisclosures(bytes: Uint8Array): DisclosureReport {
  const format = sniffFormat(bytes);
  const disclosures: Disclosure[] = [];

  // C2PA rides in a PNG caBX chunk, a JPEG APP11 JUMBF box, or a BMFF uuid box;
  // the "c2pa" JUMBF label is common to all of them.
  if (format === "png" && pngChunks(bytes).some((c) => c.type === "caBX")) {
    disclosures.push({ kind: "c2pa_manifest", location: "PNG caBX chunk", detail: "C2PA Content Credentials manifest" });
  } else if (indexOfBytes(bytes, "jumb") >= 0 && indexOfBytes(bytes, "c2pa") >= 0) {
    disclosures.push({ kind: "c2pa_manifest", location: "JUMBF box", detail: "C2PA Content Credentials manifest" });
  }

  // IPTC DigitalSourceType in XMP — the field generators use to say "AI made this".
  const text = latin1(bytes);
  for (const [term, detail] of Object.entries(DIGITAL_SOURCE_TYPES)) {
    if (new RegExp(`digitalsourcetype/${term}\\b`, "i").test(text)) {
      disclosures.push({ kind: "iptc_digital_source_type", location: "XMP metadata", detail });
    }
  }

  if (format === "png") {
    for (const { key, value } of pngTextEntries(bytes)) {
      if (GENERATOR_KEYS.has(key)) {
        disclosures.push({
          kind: "generator_parameters",
          location: `PNG text chunk "${key}"`,
          detail: `Generator settings (${value.length} chars)`,
        });
      } else if (key === "Software") {
        disclosures.push({ kind: "software_tag", location: 'PNG text chunk "Software"', detail: value.slice(0, 120) });
      }
    }
  }

  const xmpTool = /<xmp:CreatorTool>([^<]{1,120})<\/xmp:CreatorTool>|xmp:CreatorTool="([^"]{1,120})"/.exec(text);
  if (xmpTool) {
    disclosures.push({ kind: "software_tag", location: "XMP CreatorTool", detail: (xmpTool[1] ?? xmpTool[2])! });
  }

  return { format, disclosures, invisible_watermarks_unchecked: true };
}
